---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: cluster/internal-development
  url: https://github.com/makkes/flux-mc-control-plane
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 6h
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
